version: '3.2'
services:
  ssh_challenge_auth:
    build:
      context: .
      dockerfile: Dockerfile
    image: lewinc/sshd_challenge_auth
    hostname: sshd_challenge_auth
    container_name: sshd_challenge_auth
    volumes:
      - ./.ssh:/home/ssh_resources
    ports:
      - "2222:22"
